# 操作成功并且isSuccess=1 即为成功抢到  CK版本
# token有效期为24小时 记的提前更换  (支持ck或wskey自动获取token,避嫌和提高门槛就没采用)
# test 为测试模式,直接运行,方便校验token有效性  空或其他为定时模式,挂机操作  (推荐测试模式  10点准时运行程序即可,期间可反复运行) 
mode: test1
# 抢多少豆 1000|10 默认1000
bean: 1000
# 定时时间  给一分钟时间提取token
time: 59:09:00
# 持续时间 这个时间会使得窗口打印有等待时间  这是正常现象  推荐15-20
duration: 20
# 线程数量  每秒为每个ck执行多少个线程  推荐 6-8
count: 6
# pins：随意命名,标记token而已  tokens：jwt三段式的token,东东超市刷新星币兑换列表可以抓到  token数量保持在5个最佳
token:
  pins:
  - "test"
  - "pin2"
  cks:
  - "pt_key=AAJi4i6oADBRV7qlr0ofSqQKXuMrnzUyXgSYHpNc3z653SCBadIZuS7Pd5yBV5ztJmMDWdZomjA; pt_pin=jd_4300168fb404b;"
  - "ck2"
