token:
  pins:
  - pin1
  - pin2
  cks:
  - "pt_key=app_openAAJijKSWADA-tf36es-LYMNdGPzm5ADMvsFT_FO_rJnCDJvzNjWI2gSOhbtDc9qL5ra7P33BCgY;pt_pin=i_fun;"
  - "ck2"
  tokens:
mode: test
bean: "1000"
time: "59:09:00"
duration: 20
count: 6
